// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_AddToWishlist_MF(IContext context, myfirstmodule.proxies.course_upload _course_upload)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("course_upload", _course_upload == null ? null : _course_upload.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_AddToWishlist_MF").withParams(params).execute(context);
	}
	public static void aCT_Remove_from_Wishlist_MF(IContext context, myfirstmodule.proxies.course_upload _course_upload)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("course_upload", _course_upload == null ? null : _course_upload.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Remove_from_Wishlist_MF").withParams(params).execute(context);
	}
	public static void aCT_Student_Login(IContext context, myfirstmodule.proxies.Student_Login _student_Login)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Student_Login", _student_Login == null ? null : _student_Login.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Student_Login").withParams(params).execute(context);
	}
	public static void aCT_Teacher_Login(IContext context, myfirstmodule.proxies.Login_teacher _teacher_Login)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Teacher_Login", _teacher_Login == null ? null : _teacher_Login.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Teacher_Login").withParams(params).execute(context);
	}
	public static void course_uploadation_section_correction(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.course_uploadation_section_correction").withParams(params).execute(context);
	}
	public static void log_out(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.log_out").withParams(params).execute(context);
	}
	public static void teacher_login(IContext context, myfirstmodule.proxies.Login_teacher _login_teacher)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Login_teacher", _login_teacher == null ? null : _login_teacher.getMendixObject());
		Core.microflowCall("MyFirstModule.teacher_login").withParams(params).execute(context);
	}
	public static void teacher_login_1(IContext context, myfirstmodule.proxies.Login_teacher _login_teacher)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Login_teacher", _login_teacher == null ? null : _login_teacher.getMendixObject());
		Core.microflowCall("MyFirstModule.teacher_login_1").withParams(params).execute(context);
	}
	public static void teacher_register(IContext context, myfirstmodule.proxies.Registration_teacher _registration_teacher)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Registration_teacher", _registration_teacher == null ? null : _registration_teacher.getMendixObject());
		Core.microflowCall("MyFirstModule.teacher_register").withParams(params).execute(context);
	}
}