// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Entity_2 extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Entity_2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Attribute("Attribute"),
		Attribute_2("Attribute_2"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Entity_2_Image("MyFirstModule.Entity_2_Image");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Entity_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Entity_2"));
	}

	protected Entity_2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entity_2MendixObject)
	{
		super(context, entity_2MendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Entity_2", entity_2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Entity_2");
	}

	/**
	 * @deprecated Use 'Entity_2.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Entity_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Entity_2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Entity_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Entity_2(context, mendixObject);
	}

	public static myfirstmodule.proxies.Entity_2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Entity_2.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Entity_2> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Entity_2> result = new java.util.ArrayList<myfirstmodule.proxies.Entity_2>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Entity_2" + xpathConstraint))
			result.add(myfirstmodule.proxies.Entity_2.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Attribute
	 */
	public final java.lang.String getAttribute()
	{
		return getAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute
	 */
	public final java.lang.String getAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute.toString());
	}

	/**
	 * Set value of Attribute
	 * @param attribute
	 */
	public final void setAttribute(java.lang.String attribute)
	{
		setAttribute(getContext(), attribute);
	}

	/**
	 * Set value of Attribute
	 * @param context
	 * @param attribute
	 */
	public final void setAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute)
	{
		getMendixObject().setValue(context, MemberNames.Attribute.toString(), attribute);
	}

	/**
	 * @return value of Attribute_2
	 */
	public final java.lang.String getAttribute_2()
	{
		return getAttribute_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute_2
	 */
	public final java.lang.String getAttribute_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute_2.toString());
	}

	/**
	 * Set value of Attribute_2
	 * @param attribute_2
	 */
	public final void setAttribute_2(java.lang.String attribute_2)
	{
		setAttribute_2(getContext(), attribute_2);
	}

	/**
	 * Set value of Attribute_2
	 * @param context
	 * @param attribute_2
	 */
	public final void setAttribute_2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute_2)
	{
		getMendixObject().setValue(context, MemberNames.Attribute_2.toString(), attribute_2);
	}

	/**
	 * @return value of Entity_2_Image
	 */
	public final system.proxies.Image getEntity_2_Image() throws com.mendix.core.CoreException
	{
		return getEntity_2_Image(getContext());
	}

	/**
	 * @param context
	 * @return value of Entity_2_Image
	 */
	public final system.proxies.Image getEntity_2_Image(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Image result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Entity_2_Image.toString());
		if (identifier != null)
			result = system.proxies.Image.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Entity_2_Image
	 * @param entity_2_image
	 */
	public final void setEntity_2_Image(system.proxies.Image entity_2_image)
	{
		setEntity_2_Image(getContext(), entity_2_image);
	}

	/**
	 * Set value of Entity_2_Image
	 * @param context
	 * @param entity_2_image
	 */
	public final void setEntity_2_Image(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Image entity_2_image)
	{
		if (entity_2_image == null)
			getMendixObject().setValue(context, MemberNames.Entity_2_Image.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Entity_2_Image.toString(), entity_2_image.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Entity_2 that = (myfirstmodule.proxies.Entity_2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Entity_2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
