// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class ImageUpload extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.ImageUpload";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		course_name("course_name"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ImageUpload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.ImageUpload"));
	}

	protected ImageUpload(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject imageUploadMendixObject)
	{
		super(context, imageUploadMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.ImageUpload", imageUploadMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.ImageUpload");
	}

	/**
	 * @deprecated Use 'ImageUpload.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.ImageUpload initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.ImageUpload.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.ImageUpload initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ImageUpload(context, mendixObject);
	}

	public static myfirstmodule.proxies.ImageUpload load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ImageUpload.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.ImageUpload> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.ImageUpload> result = new java.util.ArrayList<myfirstmodule.proxies.ImageUpload>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.ImageUpload" + xpathConstraint))
			result.add(myfirstmodule.proxies.ImageUpload.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of course_name
	 */
	public final java.lang.String getcourse_name()
	{
		return getcourse_name(getContext());
	}

	/**
	 * @param context
	 * @return value of course_name
	 */
	public final java.lang.String getcourse_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.course_name.toString());
	}

	/**
	 * Set value of course_name
	 * @param course_name
	 */
	public final void setcourse_name(java.lang.String course_name)
	{
		setcourse_name(getContext(), course_name);
	}

	/**
	 * Set value of course_name
	 * @param context
	 * @param course_name
	 */
	public final void setcourse_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String course_name)
	{
		getMendixObject().setValue(context, MemberNames.course_name.toString(), course_name);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ImageUpload that = (myfirstmodule.proxies.ImageUpload) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.ImageUpload";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
