// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Login_teacher
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject login_teacherMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Login_teacher";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Email("Email"),
		Password("Password"),
		id_number("id_number"),
		Login_teacher_Registration_teacher("MyFirstModule.Login_teacher_Registration_teacher"),
		Login_teacher_course_upload("MyFirstModule.Login_teacher_course_upload");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Login_teacher(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Login_teacher"));
	}

	protected Login_teacher(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject login_teacherMendixObject)
	{
		if (login_teacherMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Login_teacher", login_teacherMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Login_teacher");

		this.login_teacherMendixObject = login_teacherMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Login_teacher.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Login_teacher initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Login_teacher.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Login_teacher initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Login_teacher(context, mendixObject);
	}

	public static myfirstmodule.proxies.Login_teacher load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Login_teacher.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Login_teacher> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Login_teacher> result = new java.util.ArrayList<myfirstmodule.proxies.Login_teacher>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Login_teacher" + xpathConstraint))
			result.add(myfirstmodule.proxies.Login_teacher.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of id_number
	 */
	public final java.lang.Integer getid_number()
	{
		return getid_number(getContext());
	}

	/**
	 * @param context
	 * @return value of id_number
	 */
	public final java.lang.Integer getid_number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.id_number.toString());
	}

	/**
	 * Set value of id_number
	 * @param id_number
	 */
	public final void setid_number(java.lang.Integer id_number)
	{
		setid_number(getContext(), id_number);
	}

	/**
	 * Set value of id_number
	 * @param context
	 * @param id_number
	 */
	public final void setid_number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer id_number)
	{
		getMendixObject().setValue(context, MemberNames.id_number.toString(), id_number);
	}

	/**
	 * @return value of Login_teacher_Registration_teacher
	 */
	public final myfirstmodule.proxies.Registration_teacher getLogin_teacher_Registration_teacher() throws com.mendix.core.CoreException
	{
		return getLogin_teacher_Registration_teacher(getContext());
	}

	/**
	 * @param context
	 * @return value of Login_teacher_Registration_teacher
	 */
	public final myfirstmodule.proxies.Registration_teacher getLogin_teacher_Registration_teacher(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Registration_teacher result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Login_teacher_Registration_teacher.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Registration_teacher.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Login_teacher_Registration_teacher
	 * @param login_teacher_registration_teacher
	 */
	public final void setLogin_teacher_Registration_teacher(myfirstmodule.proxies.Registration_teacher login_teacher_registration_teacher)
	{
		setLogin_teacher_Registration_teacher(getContext(), login_teacher_registration_teacher);
	}

	/**
	 * Set value of Login_teacher_Registration_teacher
	 * @param context
	 * @param login_teacher_registration_teacher
	 */
	public final void setLogin_teacher_Registration_teacher(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Registration_teacher login_teacher_registration_teacher)
	{
		if (login_teacher_registration_teacher == null)
			getMendixObject().setValue(context, MemberNames.Login_teacher_Registration_teacher.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Login_teacher_Registration_teacher.toString(), login_teacher_registration_teacher.getMendixObject().getId());
	}

	/**
	 * @return value of Login_teacher_course_upload
	 */
	public final myfirstmodule.proxies.course_upload getLogin_teacher_course_upload() throws com.mendix.core.CoreException
	{
		return getLogin_teacher_course_upload(getContext());
	}

	/**
	 * @param context
	 * @return value of Login_teacher_course_upload
	 */
	public final myfirstmodule.proxies.course_upload getLogin_teacher_course_upload(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.course_upload result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Login_teacher_course_upload.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.course_upload.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Login_teacher_course_upload
	 * @param login_teacher_course_upload
	 */
	public final void setLogin_teacher_course_upload(myfirstmodule.proxies.course_upload login_teacher_course_upload)
	{
		setLogin_teacher_course_upload(getContext(), login_teacher_course_upload);
	}

	/**
	 * Set value of Login_teacher_course_upload
	 * @param context
	 * @param login_teacher_course_upload
	 */
	public final void setLogin_teacher_course_upload(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.course_upload login_teacher_course_upload)
	{
		if (login_teacher_course_upload == null)
			getMendixObject().setValue(context, MemberNames.Login_teacher_course_upload.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Login_teacher_course_upload.toString(), login_teacher_course_upload.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return login_teacherMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Login_teacher that = (myfirstmodule.proxies.Login_teacher) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Login_teacher";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
